port:  5000
markdown: kramdown
name: "My Reps"
url: http://localhost:5000
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyAoYHdr4b5l8eOiNydo1vWrWP4Xz4e5O9Y
